### ISSUE TITLE
Can't enter the hash symbol when using an Italian keyboard

### ISSUE THREAD

**Issue by l-de-lellis** [renerocksai/sublimeless_zk#2]
Hello and thank you for writing  this great software,

I'm trying sublimeless_zk with an[ Italian keyboard ](https://commons.wikimedia.org/wiki/File:Italian_Keyboard_layout.svg) where the hash symbol is entered using the **AltGr** (third level modifier) key + **à** letter. The key combination works as expected for invoking the "all tags" saved search (**#!**) or for tag completion command (**#?**) even if no character is shown on the editor, but I cannot insert a new tag because typing  only the **#** symbol doesn't result in any character showing in the editor pane and it also truncates the first letter of the tag word (_e.g._ if I want to insert the **#zettelkasten** tag by writing directly the letters sequence I obtain "**ettelkasten**"). 

If I switch to the ENG keyboard layout (on Windows 10) all works as expected, so I suspect there is an issue with the AltGr key combination.

**Comment by renerocksai** [comment]
Interesting. Hmmm. Let me get this right:

* You can use #! and #?
* Via #? you can insert existing #tags
* You **cannot** use the # symbol in the text editors
* You did **not** try to insert a new tag in the #? selection dialog

Definitely, something weird is going on here. Seems like some UTF issue, as a first guess. 

What happens when you insert an # symbol in the editor via AltGr + à and then stop typing? Does a # show up?

**Comment by renerocksai** [comment]
Kudos you got the Windows Version running, though. I noticed, on some (like: freshly installed) Windows machines, it currently doesn't.

**Comment by renerocksai** [comment]
I hope the latest commits fixed this. See #32
