### ISSUE TITLE
list recently viewed notes

### ISSUE THREAD

**Issue by 517qf** [renerocksai/sublimeless_zk#66]
Since 0.7 you can list most recently edited notes (fix for #38). 

I wonder if this feature sould be expanded? 

Only viewing edited notes is useful, but sometimes you may want this list to include also notes that you just viewed. You should definitly keep the current function which refers only to edtied notes.

I got this idea from a review of "The Archive": "One feature The Archive desperately needs is backward and forward navigation buttons, so you can return quickly to the notes you’ve been viewing and working on." (https://welcometosherwood.wordpress.com/2018/03/24/the-archive-a-new-slip-box-for-your-notes/)

**Comment by renerocksai** [comment]
👍 Will come up with sth in 0.8
Thanks for this idea. I didn't have it on the radar, even though I recall also reading about requests for backward/forward navigation in the archive. It isn't so much of a problem in sl_zk because we have tabs, which The Archive doesn't have: you can only see one document at a time. If you don't close your tabs, you have a poor man's version of a list of recently visited notes. You get it in list form if you press ctrl / cmd  + G. Till 0.8, when you can see them in the search results.
