### ISSUE TITLE
Rename note - also apply to other notes?

### ISSUE THREAD

**Issue by 517qf** [renerocksai/sublimeless_zk#70]
When you rename a note (Ctrl+Shift+R) maybe the new name should also be inserted into other notes that contains links with descriptions? Maybe there should there be an option for this? I'm not sure if this is a good feature. I just wanted to raise your awareness.

I came to this idea because tonight when I read on takingnotenow.blogspot.com .

**Comment by renerocksai** [comment]
This is dangerous and I "refuse" to do it, however handy it might appear. It is just bound to cause "unexpected" troubles. I don't even rename the note title if it's contained within the renamed note, on purpose. A single accidental blank would make this un-reliable; you'd end up with some titles renamed, others not, maybe because there's a blank, newline character, tab, dash, added emphasis, ... inserted after the fact.

Better not touch other notes in that case.
