### ISSUE TITLE
Linking to not yet existing file causes crash

### ISSUE THREAD

**Issue by partnerwerk** [renerocksai/sublimeless_zk#98]
When I link to a new topic I want to write on with `[[linktext]]` I get a clickable link but the app is crashing. A desired outcome would be a dialogue which asks to create a new topic (Zettel). Or - at least - that the app just does nothing.

**Comment by renerocksai** [comment]
Hi, the solution you describe is roughly what the app is supposed to do, as is described [here](https://github.com/renerocksai/sublimeless_zk#implicitly-creating-a-new-note-via-a-link) in the README. Instead of popping up a dialog asking to create a new note or to confirm the title, it just creates a new note with that title and inserts a link.

I use this all the time. Can you provide an example? I just checked: [[A Text with an Ümlaut]] causes a crash. Chances are you're hitting the same bug. 

Thanks for reporting this. However, check with your provided example `[[linktext]]` to see what it would be like 😄 

That said, I am currently super busy with a research project and expect to have more time to work on this project probably in 4 weeks...

**Comment by partnerwerk** [comment]
Ah, I see. You are right. This is related to the umlaut bug. So I close this thread. Thank you for taking the time to answer despite your work load. I appreciate it. No problem to wait, but good to know about it.
